comp = NO_MATTER

{{ WEB_GRID
  items = [
    { component: HEADER, grid-area: "header" },
    { component: comp, grid-area: "content" },
    { component: FOOTER, grid-area: "footer" }
  ]
  grid-template-columns = ["1fr"]
  grid-template-rows = ["min-content", "1fr", "min-content"]
  grid-template-areas = [
    ["header"],
    ["content"],
    ["footer"]
  ]
}}

~ HEADER
# Header

~ FOOTER
Footer
